# Generated by Django 4.0.1 on 2022-02-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_days', '0002_week_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='works',
            field=models.TextField(blank=True),
        ),
    ]
