# Generated by Django 4.0.1 on 2022-02-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('day_start', models.IntegerField()),
                ('day_stop', models.IntegerField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horoscope.elements')),
            ],
        ),
    ]
